# Generated by Django 5.1.15 on 2026-03-30 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'mastery_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Markdown-formatted problem statement')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('algorithm', 'Algorithm'), ('systems', 'Systems')], default='algorithm', max_length=20)),
                ('constraints', models.TextField(blank=True, help_text='Input constraints')),
                ('hints', models.TextField(blank=True)),
                ('starter_code', models.JSONField(blank=True, default=dict)),
                ('reference_solution', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_problems', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='compute_mastery.tag')),
            ],
            options={
                'db_table': 'mastery_problems',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('cpp', 'C++'), ('rust', 'Rust')], default='cpp', max_length=10)),
                ('version', models.PositiveIntegerField()),
                ('code', models.TextField()),
                ('notes', models.TextField(blank=True, help_text="e.g., 'Added SIMD', 'Tried lock-free queue'")),
                ('is_accepted', models.BooleanField(null=True)),
                ('median_runtime_us', models.FloatField(blank=True, null=True)),
                ('peak_memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('perf_counters', models.JSONField(blank=True, default=dict)),
                ('compiler_flags', models.CharField(default='-O2 -std=c++20', max_length=100)),
                ('custom_flags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='compute_mastery.problem')),
            ],
            options={
                'db_table': 'mastery_solutions',
                'ordering': ['-version'],
                'unique_together': {('problem', 'language', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.TextField(help_text='Raw stdin input')),
                ('expected_output', models.TextField(help_text='Expected stdout output')),
                ('is_sample', models.BooleanField(default=False, help_text='Visible in problem statement')),
                ('order', models.PositiveIntegerField(default=0)),
                ('time_limit_ms', models.PositiveIntegerField(default=2000)),
                ('memory_limit_mb', models.PositiveIntegerField(default=256)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='compute_mastery.problem')),
            ],
            options={
                'db_table': 'mastery_test_cases',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JudgeResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit', 'Time Limit Exceeded'), ('memory_limit', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compile_error', 'Compile Error')], max_length=20)),
                ('actual_output', models.TextField(blank=True)),
                ('stderr_output', models.TextField(blank=True)),
                ('wall_times_us', models.JSONField(default=list)),
                ('median_time_us', models.FloatField(null=True)),
                ('min_time_us', models.FloatField(null=True)),
                ('max_time_us', models.FloatField(null=True)),
                ('std_dev_us', models.FloatField(null=True)),
                ('instructions', models.BigIntegerField(null=True)),
                ('cycles', models.BigIntegerField(null=True)),
                ('cache_misses', models.BigIntegerField(null=True)),
                ('branch_misses', models.BigIntegerField(null=True)),
                ('ipc', models.FloatField(null=True)),
                ('context_switches', models.PositiveIntegerField(null=True)),
                ('peak_memory_kb', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compute_mastery.solution')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compute_mastery.testcase')),
            ],
            options={
                'db_table': 'mastery_judge_results',
                'ordering': ['test_case__order'],
            },
        ),
    ]
