# Generated by Django 5.1.15 on 2026-03-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute_mastery', '0002_alter_problem_slug_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='llm_analysis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
