# Generated by Django 5.1.15 on 2026-02-23 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntertainmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('entertainment_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series / Short Film'), ('gaming', 'Gaming')], max_length=20)),
                ('venue', models.CharField(blank=True, help_text='e.g., HT-Screen 1 Dolby Atmos, Lab, Home', max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Personal rating 1-10', null=True)),
                ('is_scheduled', models.BooleanField(default=False, help_text='Pre-scheduled vs logged after')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entertainment_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thelife_entertainment_logs',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='thelife_ent_user_id_82d3d6_idx')],
            },
        ),
    ]
