# Generated by Django 5.1.15 on 2026-02-23 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('work_score', models.FloatField(default=0, help_text='Work efficiency score')),
                ('skill_score', models.FloatField(default=0, help_text='Skill learning score')),
                ('fitness_score', models.FloatField(default=0, help_text='Fitness/health score')),
                ('personal_score', models.FloatField(default=0, help_text='Personal time management score')),
                ('consistency_score', models.FloatField(default=0, help_text='Logging consistency score')),
                ('base_score', models.FloatField(default=0, help_text='Weighted formula score out of 100')),
                ('llm_adjustment', models.FloatField(default=0, help_text='LLM adjustment (-30 to +30)')),
                ('final_score', models.FloatField(default=0, help_text='Final score after LLM adjustment')),
                ('llm_feedback', models.TextField(blank=True, default='', help_text='LLM scrutinizer feedback for the day')),
                ('llm_processed', models.BooleanField(default=False)),
                ('total_logged_hours', models.FloatField(default=0)),
                ('total_activities', models.PositiveIntegerField(default=0)),
                ('logging_coverage', models.FloatField(default=0, help_text='% of waking hours logged')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thelife_daily_scores',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('avg_score', models.FloatField(default=0)),
                ('best_day_score', models.FloatField(default=0)),
                ('worst_day_score', models.FloatField(default=0)),
                ('total_logged_hours', models.FloatField(default=0)),
                ('days_logged', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thelife_monthly_scores',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('week_number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('avg_score', models.FloatField(default=0)),
                ('best_day_score', models.FloatField(default=0)),
                ('worst_day_score', models.FloatField(default=0)),
                ('total_logged_hours', models.FloatField(default=0)),
                ('days_logged', models.PositiveSmallIntegerField(default=0)),
                ('avg_work_score', models.FloatField(default=0)),
                ('avg_skill_score', models.FloatField(default=0)),
                ('avg_fitness_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thelife_weekly_scores',
                'ordering': ['-year', '-week_number'],
                'unique_together': {('user', 'year', 'week_number')},
            },
        ),
    ]
