# Generated by Django 5.1.15 on 2026-02-23 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(default='circle', help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(default='#00BCD4', help_text='Hex color for UI', max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Activity Categories',
                'db_table': 'thelife_activity_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='activities.activitycategory')),
            ],
            options={
                'db_table': 'thelife_activity_types',
                'ordering': ['category__sort_order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays (Mon-Fri)'), ('weekends', 'Weekends (Sat-Sun)'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday, 6=Sunday (for weekly)', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1-31 (for monthly)', null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activitytype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.activitycategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thelife_recurring_tasks',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Auto-calculated or manually entered duration in minutes')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes, reflections')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('productivity_rating', models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=3)),
                ('base_score', models.FloatField(default=0, help_text='Formula-based score for this log')),
                ('llm_adjustment', models.FloatField(default=0, help_text='LLM adjustment (-30 to +30)')),
                ('llm_feedback', models.TextField(blank=True, default='', help_text='LLM scrutinizer feedback')),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='activities.activitycategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='activities.activitytype')),
            ],
            options={
                'db_table': 'thelife_activity_logs',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['user', 'date'], name='thelife_act_user_id_b27a38_idx'), models.Index(fields=['user', 'category', 'date'], name='thelife_act_user_id_94a1d6_idx')],
            },
        ),
    ]
