# Generated by Django 5.1.15 on 2026-02-23 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Computer Architecture, Machine Learning', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='queued', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thelife_skills',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('book', 'Book'), ('course_coursera', 'Online Course (Coursera)'), ('course_udemy', 'Online Course (Udemy)'), ('course_youtube', 'Online Course (YouTube)'), ('tutorial', 'Tutorial / Blog'), ('practice', 'Practice / Hands-on'), ('podcast', 'Podcast / Audio'), ('paper', 'Research Paper'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, help_text='Link to course/resource')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('total_sections', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_sections', models.PositiveIntegerField(default=0)),
                ('total_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='skills.skill')),
            ],
            options={
                'db_table': 'thelife_skill_resources',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('start_page', models.PositiveIntegerField(blank=True, null=True)),
                ('end_page', models.PositiveIntegerField(blank=True, null=True)),
                ('sections_covered', models.CharField(blank=True, help_text='Sections/chapters covered in this session', max_length=500)),
                ('sections_count', models.PositiveIntegerField(default=0)),
                ('video_timestamp_start', models.CharField(blank=True, help_text='e.g., 1:23:45', max_length=20)),
                ('video_timestamp_end', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Session notes, key learnings')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Avg'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=3, help_text='Self-assessed session quality')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='skills.skillresource')),
            ],
            options={
                'db_table': 'thelife_skill_sessions',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
